### ISSUE TITLE
[FR] SendAI integration

### ISSUE THREAD

**Issue by CodingTux** [nerobossai/nerosdk#8]
Integrate SendAI in NeroSDK
https://www.solanaagentkit.xyz/

**Comment by 0xtarunkm** [comment]
- [ ] Create NFT Collection
- [ ] Swap Tokens
- [ ] Lend Tokens
- [ ] Stake SOL
- [ ] Fetch Token Price
- [ ] SPL Token Airdrop via ZK Compression

**Comment by CodingTux** [comment]
Draft PR: https://github.com/nerobossai/nerosdk/pull/10

**Comment by CodingTux** [comment]
Merged: https://github.com/nerobossai/nerosdk/pull/10
